### ISSUE TITLE
SecureRandom IV

### ISSUE THREAD

**Issue by ravenet** [Pakhee/Cross-platform-AES-encryption#16]
Hi,
I followed your code and AES, as per Android Developer blog, there is an issue in SecureRandom class.

http://tozny.com/blog/encrypting-strings-in-android-lets-make-better-mistakes/

So there is solution over come this issue,   so why you should not update library using https://github.com/tozny/java-aes-crypto

thanks

**Comment by navneet83** [comment]
Yes, in my blog I have linked to the bitcoin issue which happened because of this. 
Solution is to use PRNGFixes class and apply the fix: http://android-developers.blogspot.de/2013/08/some-securerandom-thoughts.html

This issue has also been discussed here.
https://github.com/Pakhee/Cross-platform-AES-encryption/issues/7

**Comment by navneet83** [comment]
Enhancement as discussed in https://github.com/Pakhee/Cross-platform-AES-encryption/issues/7

**Comment by ravenet** [comment]
Hi Naveet,

That's great. and I will make it closed.
